packages:
  - aave-test-kit
  - aave-test-suite

overrides:
  '@eslint/plugin-kit@<0.3.3': '>=0.3.3'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  ajv@<6.14.0: ^6.14.0
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  axios@<1.12.0: '>=1.12.0'
  bn.js@<5.2.3: '>=5.2.3'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cookie@<0.7.0: '>=0.7.0'
  diff@<4.0.4: '>=4.0.4'
  eslint@<9.26.0: '>=9.26.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'
  minimatch@<3.0.5: '>=3.0.5'
  minimatch@<10.2.3: '>=10.2.3'
  minimist@>=1.0.0 <1.2.6: '>=1.2.6'
  postcss@<7.0.36: '>=7.0.36'
  postcss@<8.4.31: '>=8.4.31'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  tmp@<=0.2.3: '>=0.2.4'
  trim@<0.0.3: '>=0.0.3'
