[package]
name = "AavePool"
version = "1.1.0"
upgrade_policy = "compatible"
authors = []

[addresses]
aave_pool = '_'
gho = "_"
gho_config = "_"
gho_acl = "_"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AaveAcl = { local = "./aave-acl" }
AaveConfig = { local = "./aave-config" }
AaveMath = { local = "./aave-math" }
AaveOracle = { local = "./aave-oracle" }
Gho_Token = { git = "https://github.com/aave/aptos-aave-gho", subdir = "Gho", rev = "main" }

[dev-dependencies]
AaveMockUnderlyings = { local = "./aave-mock-underlyings" }
