[package]
name = "Examples"
version = "1.1.0"
upgrade_policy = "compatible"
authors = []

[addresses]

[dev-addresses]

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "mainnet" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "mainnet" }
AaveAcl = { local = "../aave-core/aave-acl" }
AaveConfig = { local = "../aave-core/aave-config" }
AaveOracle = { local = "../aave-core/aave-oracle" }
AaveData = { local = "../aave-core/aave-data" }
AavePool = { local = "../aave-core" }
Gho_Token = { git = "https://github.com/aave/aptos-aave-gho", subdir = "Gho", rev = "main" }

[dev-dependencies]
