name: Examples

on:
  pull_request:
  merge_group:
    branches:
      - main

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTIONS: true
  MOVE_VERSION: 2.2
  COMPILER_VERSION: 2.0
  ARTIFACTS_LEVEL: all

jobs:
  compile-examples:
    name: Compile All Examples
    runs-on: Larger-Github-Runners
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install Aptos CLI (script)
        shell: bash
        run: |
          set -Eeuo pipefail
          curl -fsSL "https://aptos.dev/scripts/install_cli.sh" | sh
          echo "$HOME/.aptos/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Verify Aptos
        shell: bash
        run: |
          set -Eeuo pipefail
          export PATH="$HOME/.aptos/bin:$HOME/.local/bin:$PATH"
          aptos --version
          aptos update movefmt

      - name: Run Aptos Compile All Examples
        working-directory: examples
        run: make compile
