permissions:
  contents: read

name: Examples

on:
  pull_request:
  merge_group:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTIONS: true
  MOVE_VERSION: 2.1
  COMPILER_VERSION: 2.0
  ARTIFACTS_LEVEL: all

jobs:
  compile-examples:
    name: Compile All Examples
    runs-on: Larger-Github-Runners
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GH_ACTIONS_APP_ID }}
          private-key: ${{ secrets.GH_ACTIONS_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "aptos-aave-gho"

      - name: Install Aptos CLI
        uses: ./.github/actions/install-aptos-cli
        with:
          version: "7.7.0"

      - name: Run Aptos Compile All Examples
        working-directory: examples
        run: make compile
