name: Examples

on:
  pull_request:
  merge_group:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTIONS: true
  APTOS_NETWORK: local
  MOVE_VERSION: 2.1
  COMPILER_VERSION: 2.0
  ARTIFACTS_LEVEL: all
  DEFAULT_FUND_AMOUNT: 40000000
  DEFAULT_FUNDER_PRIVATE_KEY: ${{ secrets.GH_DEFAULT_FUNDER_PRIVATE_KEY }}

  # aave profiles
  AAVE_ACL_PRIVATE_KEY: ${{ secrets.GH_AAVE_ACL_PRIVATE_KEY }}
  AAVE_CONFIG_PRIVATE_KEY: ${{ secrets.GH_AAVE_CONFIG_PRIVATE_KEY }}
  AAVE_MATH_PRIVATE_KEY: ${{ secrets.GH_AAVE_MATH_PRIVATE_KEY }}
  AAVE_ORACLE_PRIVATE_KEY: ${{ secrets.GH_AAVE_ORACLE_PRIVATE_KEY }}
  AAVE_POOL_PRIVATE_KEY: ${{ secrets.GH_AAVE_POOL_PRIVATE_KEY }}
  AAVE_MOCK_UNDERLYING_TOKENS_PRIVATE_KEY: ${{ secrets.GH_AAVE_MOCK_UNDERLYING_TOKENS_PRIVATE_KEY }}
  AAVE_LARGE_PACKAGES_PRIVATE_KEY: ${{ secrets.GH_AAVE_LARGE_PACKAGES_PRIVATE_KEY }}
  AAVE_DATA_PRIVATE_KEY: ${{ secrets.GH_AAVE_DATA_PRIVATE_KEY }}
  AAVE_DATA_FEEDS_PRIVATE_KEY: ${{ secrets.GH_AAVE_DATA_FEEDS_PRIVATE_KEY }}
  AAVE_PLATFORM_PRIVATE_KEY: ${{ secrets.GH_AAVE_PLATFORM_PRIVATE_KEY }}

jobs:
  compile-examples:
    name: Run Aptos Unit Tests
    runs-on: Larger-Github-Runners
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install Aptos CLI
        uses: ./.github/actions/install-aptos-cli
        with:
          version: "7.7.0"

      - name: Run Aptos Compile All Examples
        working-directory: examples
        run: make compile
